import fs from "node:fs";
import path from "node:path";
import { Contract, ContractFactory, JsonRpcProvider, Wallet } from "ethers";

const root = process.cwd();
const rpcUrl = process.env.CREDITCOIN_RPC_URL;
const privateKey = process.env.CREDITCOIN_DEPLOYER_PRIVATE_KEY;
if (!rpcUrl || !privateKey) throw new Error("CREDITCOIN_RPC_URL and CREDITCOIN_DEPLOYER_PRIVATE_KEY are required");
const financingAddress = "0xe378E93D5eC4dDa719355c5274d85e97c3a0A500";
const sourceRegistryAddress = "0xE3e0b01141860541B7247f0E05b1Ea6cd60556BE";
const artifact = JSON.parse(fs.readFileSync(path.join(root, "artifacts/contracts/AttestcoinAdapter.json"), "utf8"));
const provider = new JsonRpcProvider(rpcUrl);
const wallet = new Wallet(privateKey, provider);
const network = await provider.getNetwork();
if (network.chainId !== 102031n) throw new Error(`Unexpected Creditcoin chain: ${network.chainId}`);
const factory = new ContractFactory(artifact.abi, artifact.bytecode, wallet);
const adapter = await factory.deploy(financingAddress, sourceRegistryAddress);
await adapter.waitForDeployment();
const adapterAddress = await adapter.getAddress();
const deployTx = adapter.deploymentTransaction();
const financingAbi = ["function setAttestor(address account, bool allowed) external", "function attestors(address) view returns (bool)"];
const financing = new Contract(financingAddress, financingAbi, wallet);
const authorizeTx = await financing.setAttestor(adapterAddress, true);
const authorizeReceipt = await authorizeTx.wait();
const manifestPath = path.join(root, "deployments/manifest.json");
const manifest = JSON.parse(fs.readFileSync(manifestPath, "utf8"));
manifest.networks.creditcoin.attestcoinAdapter = adapterAddress;
manifest.networks.creditcoin.attestcoinAdapterDeploymentTx = deployTx?.hash ?? null;
manifest.networks.creditcoin.attestcoinAdapterAuthorizationTx = authorizeReceipt?.hash ?? authorizeTx.hash;
manifest.networks.creditcoin.attestcoinAdapterSourceRegistry = sourceRegistryAddress;
fs.writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
console.log(`AttestcoinAdapter deployed at ${adapterAddress}`);
console.log(`Deployment tx: ${deployTx?.hash ?? "unknown"}`);
console.log(`setAttestor authorization tx: ${authorizeReceipt?.hash ?? authorizeTx.hash}`);
